services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017

  app:
    build: .
    container_name: note_api
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./.env:/app/.env
